import { Code2, MapPin, Smartphone, Sparkles } from 'lucide-react'

export default function About() {
  return <section id="apropos" className="container-page scroll-mt-24 py-16 sm:py-20 lg:py-24" data-reveal>
    <div className="grid gap-8 sm:gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center">
      <div className="relative mx-auto aspect-square w-full max-w-sm overflow-hidden rounded-[28px] border border-white/[0.08] bg-gradient-to-br from-cyan-400/15 via-[#0b1516] to-[#06090d] p-5 sm:rounded-[32px] sm:p-8"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-cyan-400/15 blur-3xl"/><div className="grid h-full place-items-center rounded-[20px] border border-white/[0.07] bg-black/20 sm:rounded-[24px]"><div className="px-3 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-cyan-400/30 bg-cyan-400/10 font-display text-3xl font-bold text-cyan-400 sm:h-24 sm:w-24 sm:text-4xl">OS</div><p className="mt-5 font-display text-lg font-semibold text-white sm:text-xl">O'nel iloris SEGBOZO</p><p className="mt-1 text-xs text-slate-500 sm:text-sm">Software & Mobile Developer</p></div></div></div>
      <div><p className="eyebrow">À propos de moi</p><h2 className="section-title">Je transforme des idées en <span className="text-cyan-400">solutions concrètes.</span></h2><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400">Développeur logiciel avec un intérêt particulier pour le mobile, le backend et les systèmes intelligents. J’aime comprendre les besoins réels, structurer des solutions simples et construire des applications utiles, maintenables et agréables à utiliser.</p><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-500">Je souhaite approfondir les architectures mobiles modernes, les API robustes et l’intelligence appliquée aux produits numériques. Mon objectif : participer à des projets qui ont un impact mesurable sur leurs utilisateurs.</p>
        <div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="glass flex items-center gap-3 rounded-2xl p-4 transition hover:-translate-y-1 hover:border-cyan-400/30"><Smartphone size={18} className="text-cyan-400"/><span className="text-xs text-slate-300">Mobile first</span></div><div className="glass flex items-center gap-3 rounded-2xl p-4 transition hover:-translate-y-1 hover:border-cyan-400/30"><Code2 size={18} className="text-cyan-400"/><span className="text-xs text-slate-300">Clean code</span></div><div className="glass flex items-center gap-3 rounded-2xl p-4 transition hover:-translate-y-1 hover:border-cyan-400/30"><Sparkles size={18} className="text-cyan-400"/><span className="text-xs text-slate-300">Curiosité</span></div></div>
        <p className="mt-6 inline-flex items-center gap-2 text-xs text-slate-500"><MapPin size={15} className="text-cyan-400"/>Localisation à renseigner</p>
      </div>
    </div>
  </section>
}
