import { Award, Calendar, Download, GraduationCap } from 'lucide-react'

export default function Education() {
  return <section id="formation" className="container-page scroll-mt-24 py-24" data-reveal>
    <div className="grid gap-6 lg:grid-cols-2">
      <article className="glass group rounded-3xl p-7 transition-all duration-500 hover:-translate-y-1 hover:border-cyan-400/30 sm:p-9"><div className="flex items-center gap-4"><span className="rounded-2xl bg-cyan-400/10 p-4 text-cyan-400 transition group-hover:rotate-6"><GraduationCap size={25}/></span><div><p className="eyebrow">Formation</p><h2 className="mt-2 text-2xl font-semibold text-white">Parcours informatique</h2></div></div><p className="mt-7 text-sm leading-6 text-slate-400">Ajoute ici ton diplôme actuel, ton établissement, tes années d’études et ta spécialité.</p><div className="mt-6 flex items-center gap-2 border-t border-white/[0.06] pt-5 text-xs text-slate-500"><Calendar size={15} className="text-cyan-400"/>Dates à renseigner</div></article>
      <article id="certifications" className="glass group rounded-3xl p-7 transition-all duration-500 hover:-translate-y-1 hover:border-cyan-400/30 sm:p-9"><div className="flex items-center gap-4"><span className="rounded-2xl bg-cyan-400/10 p-4 text-cyan-400 transition group-hover:rotate-6"><Award size={25}/></span><div><p className="eyebrow">Certifications</p><h2 className="mt-2 text-2xl font-semibold text-white">Formations complémentaires</h2></div></div><p className="mt-7 text-sm leading-6 text-slate-400">Cette section accueillera uniquement tes certifications réelles : Flutter, Python, Git, UML ou autres.</p><p className="mt-6 border-t border-white/[0.06] pt-5 text-xs text-slate-600">Aucune certification non confirmée n’est affichée.</p></article>
    </div>
    <div id="cv" className="mt-6 overflow-hidden rounded-3xl border border-cyan-400/20 bg-gradient-to-r from-cyan-400/10 via-cyan-400/[0.04] to-transparent p-7 sm:flex sm:items-center sm:justify-between sm:p-9"><div><p className="eyebrow">Curriculum vitæ</p><h2 className="mt-2 text-2xl font-semibold text-white">Envie d’en savoir plus sur mon parcours ?</h2><p className="mt-2 text-sm text-slate-500">Consultez la version complète de mon profil professionnel.</p></div><a href="/cv-segbozo-onel.pdf" download className="mt-6 inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-semibold text-black transition hover:-translate-y-1 hover:bg-cyan-300 hover:shadow-glow sm:mt-0"><Download size={17}/>Télécharger mon CV</a></div>
  </section>
}
