import { ArrowUpRight, Github, Landmark, ListChecks, ShieldCheck, Target } from 'lucide-react'

const projects = [
  { title: 'Application mobile de tontine', icon: Landmark, problem: 'Digitaliser une gestion souvent manuelle et rendre les cotisations plus transparentes.', description: 'Application Flutter pour gérer les membres, cotisations, échéances et l’historique des transactions d’une tontine.', features: ['Gestion des membres', 'Calendrier des cotisations', 'Notifications', 'Gestion des tours'], tags: ['Flutter', 'Dart', 'Firebase'] },
  { title: 'Détection de transactions suspectes', icon: ShieldCheck, problem: 'Aider à identifier les opérations atypiques dans un flux de transactions.', description: 'Système d’analyse orienté règles permettant d’étudier et de signaler les comportements potentiellement suspects.', features: ['Moteur de règles', 'Analyse des opérations', 'Signalement', 'Historique'], tags: ['Python', 'Rule Engine', 'RETE / PHReAK'] },
  { title: 'Task Manager App', icon: ListChecks, problem: 'Centraliser les tâches quotidiennes dans une expérience mobile claire et rapide.', description: 'Application de productivité avec interface personnalisée, navigation intuitive et gestion d’état réactive.', features: ['Création de tâches', 'Suivi des statuts', 'Filtres', 'Interface responsive'], tags: ['Flutter', 'Dart', 'Provider'] },
  { title: 'Number Guessing Game', icon: Target, problem: 'Mettre en pratique la logique algorithmique dans une interface interactive.', description: 'Jeu mobile avec validation en temps réel et retours visuels précis à chaque tentative.', features: ['Logique de jeu', 'Validation instantanée', 'Score', 'Nouvelle partie'], tags: ['Flutter', 'Dart', 'Algorithms'] },
]

export default function Projects() {
  return <section id="projets" className="container-page scroll-mt-24 py-16 sm:py-20 lg:py-24" data-reveal>
    <div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Ce que j’ai construit</p><h2 className="section-title">Mes <span className="text-cyan-400">Projets récents.</span></h2></div><p className="max-w-md text-sm leading-6 text-slate-500 md:text-right">Des réalisations qui répondent à des problèmes concrets avec une approche moderne et structurée.</p></div>
    <div className="grid gap-6 md:grid-cols-2">{projects.map(({ title, icon: Icon, problem, description, features, tags }, index) => <article key={title} className="glass group overflow-hidden rounded-[28px] transition-all duration-500 hover:-translate-y-2 hover:border-cyan-400/35 hover:shadow-[0_24px_70px_rgba(0,255,180,.09)]">
      <div className="relative flex h-52 items-center justify-center overflow-hidden bg-gradient-to-br from-cyan-400/15 via-emerald-500/[0.04] to-transparent"><div className="absolute inset-0 grid-overlay opacity-60"/><span className="absolute right-5 top-4 font-display text-6xl font-bold text-white/[0.04]">0{index + 1}</span><div className="relative flex h-24 w-24 items-center justify-center rounded-[26px] border border-white/10 bg-black/30 text-cyan-400 backdrop-blur-xl transition duration-700 group-hover:rotate-6 group-hover:scale-110 group-hover:border-cyan-400/40 group-hover:shadow-[0_0_50px_rgba(0,255,180,.16)]"><Icon size={40}/></div></div>
      <div className="p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><h3 className="text-2xl font-semibold text-white transition group-hover:text-cyan-300">{title}</h3><ArrowUpRight className="shrink-0 text-slate-600 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-cyan-400" size={20}/></div><p className="mt-4 text-xs font-medium uppercase tracking-wider text-cyan-400">Le besoin</p><p className="mt-2 text-sm leading-6 text-slate-500">{problem}</p><p className="mt-4 text-sm leading-6 text-slate-300">{description}</p><ul className="mt-5 grid grid-cols-2 gap-2">{features.map(feature => <li key={feature} className="text-xs text-slate-500 before:mr-2 before:text-cyan-400 before:content-['•']">{feature}</li>)}</ul><div className="mt-6 flex flex-wrap gap-2">{tags.map(tag => <span key={tag} className="tech-tag transition hover:border-cyan-400/40 hover:text-cyan-300">{tag}</span>)}</div><div className="mt-7 flex gap-5 border-t border-white/[0.06] pt-5"><a href="https://github.com/Onel7" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs text-slate-400 transition hover:text-white"><Github size={15}/>GitHub</a><a href="#contact" className="inline-flex items-center gap-2 text-xs text-cyan-400 transition hover:translate-x-1">Voir le projet <ArrowUpRight size={14}/></a></div></div>
    </article>)}</div>
  </section>
}
