import { Check } from 'lucide-react'
import { skills } from '../data'

export default function Skills() {
  return <section id="competences" className="scroll-mt-24 border-y border-white/[0.05] bg-slate-950/35 py-16 sm:py-20 lg:py-24" data-reveal><div className="container-page">
    <p className="eyebrow">Technologies & outils</p><h2 className="section-title">Ma Stack <span className="text-cyan-400">Technique.</span></h2><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-500">Un écosystème d’outils modernes et performants pour construire des solutions de bout en bout.</p>
    <div className="mt-12 grid gap-5 md:grid-cols-3">{skills.map((skill) => { const Icon = skill.icon; return <article key={skill.title} className="glass group relative overflow-hidden rounded-3xl p-6 transition-all duration-500 hover:-translate-y-2 hover:border-cyan-400/35 hover:shadow-[0_20px_60px_rgba(0,255,180,.08)]"><div className="absolute -right-16 -top-16 h-36 w-36 rounded-full bg-cyan-400/0 blur-3xl transition duration-500 group-hover:bg-cyan-400/10"/><div className="relative flex items-center justify-between"><span className="rounded-xl border border-white/[0.07] bg-black/20 p-3 text-cyan-400 transition duration-500 group-hover:rotate-6 group-hover:scale-110 group-hover:border-cyan-400/30"><Icon size={22}/></span><span className="font-display text-4xl font-bold text-white/[0.04] transition group-hover:text-cyan-400/10">{skill.index}</span></div><h3 className="relative mt-6 text-lg font-semibold text-white transition group-hover:text-cyan-300">{skill.title}</h3><ul className="relative mt-6 space-y-3.5">{skill.items.map(item => <li key={item} className="flex items-start gap-3 text-sm text-slate-400 transition duration-300 hover:translate-x-1 hover:text-white"><Check size={14} className="mt-0.5 shrink-0 text-cyan-500" />{item}</li>)}</ul></article> })}</div>
  </div></section>
}
